# Generated by Django 4.1.3 on 2022-11-14 17:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default='null'),
            preserve_default=False,
        ),
    ]
